export const TOURNAMENT_INFO = {
  name: "FFSA CDS",
  fullName: "Free Fire South Asia Clash Domination Series",
  tagline: "South Asia's Ultimate Clash Squad Championship",
  prizePool: 150000,
  teams: 12,
  game: "Free Fire MAX (Clash Squad)",
  region: "South Asia",
};

export const PRIZE_BREAKDOWN = [
  { place: "1st", amount: 30000, percentage: "20%" },
  { place: "2nd", amount: 22500, percentage: "15%" },
  { place: "3rd", amount: 19500, percentage: "13%" },
  { place: "4th", amount: 15000, percentage: "10%" },
  { place: "5th-6th", amount: 6750, percentage: "4.5% (each)", teamAmount: 3375 },
  { place: "7th-8th", amount: 5250, percentage: "3.5% (each)", teamAmount: 2625 },
  { place: "9th-10th", amount: 3750, percentage: "2.5% (each)", teamAmount: 1875 },
  { place: "11th-12th", amount: 3000, percentage: "2% (each)", teamAmount: 1500 },
];

export const BONUS_POOL = [
  { award: "Finals MVP", amount: 8250, percentage: "5.5%" },
  { award: "Tournament MVP", amount: 7500, percentage: "5%" },
  { award: "Best IGL", amount: 5250, percentage: "3.5%" },
  { award: "Most Eliminations", amount: 4500, percentage: "3%" },
];

export const TEAMS = [
  {
    id: 1,
    name: "Team Alpha",
    region: "India",
    logo: "🔥",
    description: "Dominating the Indian circuit with precision gameplay",
  },
  {
    id: 2,
    name: "Dragon Force",
    region: "India",
    logo: "🐉",
    description: "Masters of aggressive rotations and mid-game control",
  },
  {
    id: 3,
    name: "Phoenix Rising",
    region: "India",
    logo: "🔱",
    description: "Comeback kings of the South Asia region",
  },
  {
    id: 4,
    name: "Bengal Tigers",
    region: "Bangladesh",
    logo: "🐯",
    description: "Bangladesh's tactical powerhouse",
  },
  {
    id: 5,
    name: "Dhaka Elite",
    region: "Bangladesh",
    logo: "⚡",
    description: "Fast-paced aggressive gameplay specialists",
  },
  {
    id: 6,
    name: "Storm Chasers",
    region: "Bangladesh",
    logo: "⛈️",
    description: "Unpredictable and versatile squad",
  },
  {
    id: 7,
    name: "Everest Warriors",
    region: "Nepal",
    logo: "⛏️",
    description: "Nepal's mountain-strong defenders",
  },
  {
    id: 8,
    name: "Kathmandu Kings",
    region: "Nepal",
    logo: "👑",
    description: "Royalty of Nepalese esports",
  },
  {
    id: 9,
    name: "Himalayan Apex",
    region: "Nepal",
    logo: "🏔️",
    description: "Reaching the peak of competitive excellence",
  },
  {
    id: 10,
    name: "Karachi Titans",
    region: "Pakistan",
    logo: "🗿",
    description: "Pakistan's formidable gaming force",
  },
  {
    id: 11,
    name: "Lahore Legends",
    region: "Pakistan",
    logo: "🌟",
    description: "Legendary gameplay and consistency",
  },
  {
    id: 12,
    name: "Islamabad Fury",
    region: "Pakistan",
    logo: "⚔️",
    description: "Fierce competitors from the northern capital",
  },
];

export const STANDINGS = [
  {
    rank: 1,
    teamId: 1,
    teamName: "Team Alpha",
    region: "India",
    wins: 14,
    losses: 1,
    roundDiff: "+45",
    points: 28,
  },
  {
    rank: 2,
    teamId: 2,
    teamName: "Dragon Force",
    region: "India",
    wins: 13,
    losses: 2,
    roundDiff: "+38",
    points: 26,
  },
  {
    rank: 3,
    teamId: 4,
    teamName: "Bengal Tigers",
    region: "Bangladesh",
    wins: 12,
    losses: 3,
    roundDiff: "+32",
    points: 24,
  },
  {
    rank: 4,
    teamId: 7,
    teamName: "Everest Warriors",
    region: "Nepal",
    wins: 11,
    losses: 4,
    roundDiff: "+25",
    points: 22,
  },
  {
    rank: 5,
    teamId: 3,
    teamName: "Phoenix Rising",
    region: "India",
    wins: 10,
    losses: 5,
    roundDiff: "+18",
    points: 20,
  },
  {
    rank: 6,
    teamId: 10,
    teamName: "Karachi Titans",
    region: "Pakistan",
    wins: 9,
    losses: 6,
    roundDiff: "+12",
    points: 18,
  },
  {
    rank: 7,
    teamId: 5,
    teamName: "Dhaka Elite",
    region: "Bangladesh",
    wins: 8,
    losses: 7,
    roundDiff: "+8",
    points: 16,
  },
  {
    rank: 8,
    teamId: 8,
    teamName: "Kathmandu Kings",
    region: "Nepal",
    wins: 7,
    losses: 8,
    roundDiff: "-5",
    points: 14,
  },
  {
    rank: 9,
    teamId: 11,
    teamName: "Lahore Legends",
    region: "Pakistan",
    wins: 6,
    losses: 9,
    roundDiff: "-12",
    points: 12,
  },
  {
    rank: 10,
    teamId: 6,
    teamName: "Storm Chasers",
    region: "Bangladesh",
    wins: 5,
    losses: 10,
    roundDiff: "-18",
    points: 10,
  },
  {
    rank: 11,
    teamId: 9,
    teamName: "Himalayan Apex",
    region: "Nepal",
    wins: 4,
    losses: 11,
    roundDiff: "-25",
    points: 8,
  },
  {
    rank: 12,
    teamId: 12,
    teamName: "Islamabad Fury",
    region: "Pakistan",
    wins: 3,
    losses: 12,
    roundDiff: "-32",
    points: 6,
  },
];

export const SCHEDULE = {
  "Week 1: League Stage": [
    {
      id: 1,
      day: "Day 1",
      date: "2024-04-07",
      matches: [
        { id: 1, team1: "Team Alpha", team2: "Dragon Force", time: "14:00", format: "BO1", status: "completed", result: "2-5" },
        { id: 2, team1: "Phoenix Rising", team2: "Bengal Tigers", time: "15:00", format: "BO1", status: "completed", result: "4-6" },
        { id: 3, team1: "Dhaka Elite", team2: "Storm Chasers", time: "16:00", format: "BO1", status: "completed", result: "5-5" },
        { id: 4, team1: "Everest Warriors", team2: "Kathmandu Kings", time: "17:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 5, team1: "Himalayan Apex", team2: "Karachi Titans", time: "18:00", format: "BO1", status: "completed", result: "3-7" },
        { id: 6, team1: "Lahore Legends", team2: "Islamabad Fury", time: "19:00", format: "BO1", status: "completed", result: "5-5" },
      ],
    },
    {
      id: 2,
      day: "Day 2",
      date: "2024-04-08",
      matches: [
        { id: 7, team1: "Team Alpha", team2: "Bengal Tigers", time: "14:00", format: "BO1", status: "completed", result: "7-3" },
        { id: 8, team1: "Dragon Force", team2: "Everest Warriors", time: "15:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 9, team1: "Phoenix Rising", team2: "Karachi Titans", time: "16:00", format: "BO1", status: "completed", result: "5-5" },
        { id: 10, team1: "Dhaka Elite", team2: "Kathmandu Kings", time: "17:00", format: "BO1", status: "completed", result: "4-6" },
        { id: 11, team1: "Storm Chasers", team2: "Lahore Legends", time: "18:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 12, team1: "Himalayan Apex", team2: "Islamabad Fury", time: "19:00", format: "BO1", status: "completed", result: "2-8" },
      ],
    },
    {
      id: 3,
      day: "Day 3",
      date: "2024-04-09",
      matches: [
        { id: 13, team1: "Team Alpha", team2: "Everest Warriors", time: "14:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 14, team1: "Dragon Force", team2: "Karachi Titans", time: "15:00", format: "BO1", status: "completed", result: "5-5" },
        { id: 15, team1: "Phoenix Rising", team2: "Dhaka Elite", time: "16:00", format: "BO1", status: "completed", result: "7-3" },
        { id: 16, team1: "Bengal Tigers", team2: "Kathmandu Kings", time: "17:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 17, team1: "Storm Chasers", team2: "Islamabad Fury", time: "18:00", format: "BO1", status: "completed", result: "4-6" },
        { id: 18, team1: "Himalayan Apex", team2: "Lahore Legends", time: "19:00", format: "BO1", status: "completed", result: "5-5" },
      ],
    },
    {
      id: 4,
      day: "Day 4",
      date: "2024-04-10",
      matches: [
        { id: 19, team1: "Team Alpha", team2: "Karachi Titans", time: "14:00", format: "BO1", status: "completed", result: "7-3" },
        { id: 20, team1: "Dragon Force", team2: "Dhaka Elite", time: "15:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 21, team1: "Phoenix Rising", team2: "Himalayan Apex", time: "16:00", format: "BO1", status: "completed", result: "8-2" },
        { id: 22, team1: "Bengal Tigers", team2: "Lahore Legends", time: "17:00", format: "BO1", status: "completed", result: "7-3" },
        { id: 23, team1: "Storm Chasers", team2: "Everest Warriors", time: "18:00", format: "BO1", status: "completed", result: "3-7" },
        { id: 24, team1: "Kathmandu Kings", team2: "Islamabad Fury", time: "19:00", format: "BO1", status: "completed", result: "5-5" },
      ],
    },
    {
      id: 5,
      day: "Day 5",
      date: "2024-04-11",
      matches: [
        { id: 25, team1: "Team Alpha", team2: "Storm Chasers", time: "14:00", format: "BO1", status: "completed", result: "8-2" },
        { id: 26, team1: "Dragon Force", team2: "Kathmandu Kings", time: "15:00", format: "BO1", status: "completed", result: "6-4" },
        { id: 27, team1: "Phoenix Rising", team2: "Islamabad Fury", time: "16:00", format: "BO1", status: "completed", result: "7-3" },
        { id: 28, team1: "Bengal Tigers", team2: "Himalayan Apex", time: "17:00", format: "BO1", status: "completed", result: "8-2" },
        { id: 29, team1: "Dhaka Elite", team2: "Karachi Titans", time: "18:00", format: "BO1", status: "completed", result: "4-6" },
        { id: 30, team1: "Everest Warriors", team2: "Lahore Legends", time: "19:00", format: "BO1", status: "completed", result: "6-4" },
      ],
    },
  ],
  "Week 2: Play-Ins": [
    {
      id: 6,
      day: "Play-Ins",
      date: "2024-04-14",
      matches: [
        { id: 31, team1: "5th Place", team2: "6th Place", time: "14:00", format: "BO3", status: "upcoming" },
        { id: 32, team1: "Wildcard", team2: "8th Place", time: "16:00", format: "BO3", status: "upcoming" },
        { id: 33, team1: "Winner", team2: "7th Place", time: "18:00", format: "BO3", status: "upcoming" },
      ],
    },
  ],
  "Week 3: Playoffs & Finals": [
    {
      id: 7,
      day: "Playoffs",
      date: "2024-04-17",
      matches: [
        { id: 34, team1: "3rd Place", team2: "Play-Ins Qualifier", time: "14:00", format: "BO3", status: "upcoming" },
        { id: 35, team1: "4th Place", team2: "Play-Ins Qualifier", time: "16:00", format: "BO3", status: "upcoming" },
      ],
    },
    {
      id: 8,
      day: "Semi-Finals & Finals",
      date: "2024-04-19",
      matches: [
        { id: 36, team1: "1st Place", team2: "2nd Place", time: "14:00", format: "BO7", status: "upcoming", description: "Semi Final 1" },
        { id: 37, team1: "Playoff Winner 1", team2: "Playoff Winner 2", time: "17:00", format: "BO5", status: "upcoming", description: "Playoff Clash" },
        { id: 38, team1: "Semi Final 1 Loser", team2: "Playoff Clash Winner", time: "20:00", format: "BO7", status: "upcoming", description: "Semi Final 2" },
        { id: 39, team1: "Semi Final 1 Winner", team2: "Semi Final 2 Winner", time: "23:30", format: "BO11", status: "upcoming", description: "Grand Final" },
      ],
    },
  ],
};

export const STATS = {
  tournamentMVP: [
    { rank: 1, playerName: "Alpha_Pro", teamId: 1, teamName: "Team Alpha", points: 1250 },
    { rank: 2, playerName: "Dragon_King", teamId: 2, teamName: "Dragon Force", points: 1180 },
    { rank: 3, playerName: "Tiger_Strike", teamId: 4, teamName: "Bengal Tigers", points: 1050 },
  ],
  finalsMVP: [
    { rank: 1, playerName: "Phoenix_Elite", teamId: 3, teamName: "Phoenix Rising", points: 580 },
  ],
  bestIGL: [
    { rank: 1, playerName: "Alpha_IGL", teamId: 1, teamName: "Team Alpha", callAccuracy: "94%" },
    { rank: 2, playerName: "Dragon_Caller", teamId: 2, teamName: "Dragon Force", callAccuracy: "91%" },
    { rank: 3, playerName: "Bengal_Commander", teamId: 4, teamName: "Bengal Tigers", callAccuracy: "88%" },
  ],
  mostEliminations: [
    { rank: 1, teamName: "Team Alpha", eliminations: 245, averagePerMatch: 17.5 },
    { rank: 2, teamName: "Dragon Force", eliminations: 218, averagePerMatch: 15.6 },
    { rank: 3, teamName: "Bengal Tigers", eliminations: 195, averagePerMatch: 13.9 },
  ],
};

export const BRACKET_STRUCTURE = {
  playIns: [
    { team1: "5th Place", team2: "6th Place", winner: "Play-In Winner" },
  ],
  semifinals: [
    {
      id: 1,
      team1: "1st Place",
      team2: "Play-In Winner",
      teams: ["Team Alpha", "TBD"],
      winner: null,
    },
    {
      id: 2,
      team1: "2nd Place",
      team2: "3rd Place",
      teams: ["Dragon Force", "Bengal Tigers"],
      winner: null,
    },
  ],
  finals: {
    team1: "Semi 1 Winner",
    team2: "Semi 2 Winner",
    format: "BO11",
    date: "2024-04-20",
  },
};
